name: core_module
description: A new Flutter package project.
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  dependency_module:
    path: ../dependency_module

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
