name: dependency_module
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cached_network_image: ^3.2.1
  styled_text: ^5.1.0

  # Structure
  dartz: ^0.10.1
  flutter_modular: ^5.0.3
  flutter_bloc: ^8.0.1
  flutter_svg: ^1.1.3

  # Core
  dio: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
