name: will_design_system
description: A new Flutter package project.
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dependency_module:
    path: ../dependency_module
  core_module:
    path: ../core_module

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/icons/

  fonts:
    - family: IBMPlexSans
      fonts:
        - asset: assets/fonts/IBM_plex_sans/IBMPlexSans-Regular.ttf
        - asset: assets/fonts/IBM_plex_sans/IBMPlexSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/IBM_plex_sans/IBMPlexSans-Italic.ttf
          style: italic
        - asset: assets/fonts/IBM_plex_sans/IBMPlexSans-Light.ttf
          weight: 300
        - asset: assets/fonts/IBM_plex_sans/IBMPlexSans-SemiBold.ttf
          weight: 600

    - family: DancingScript
      fonts:
        - asset: assets/fonts/Dancing_Script/DancingScript-Bold.ttf
          weight: 700
        - asset: assets/fonts/Dancing_Script/DancingScript-Medium.ttf
        - asset: assets/fonts/Dancing_Script/DancingScript-Regular.ttf
          weight: 300
        - asset: assets/fonts/Dancing_Script/DancingScript-SemiBold.ttf
          weight: 600
